version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 109832253823.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t test-sabc -f docker/Dockerfile .
      - docker tag test-sabc:latest 109832253823.dkr.ecr.us-west-2.amazonaws.com/test-sabc:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 109832253823.dkr.ecr.us-west-2.amazonaws.com/test-sabc:latest