AWSTemplateFormatVersion: "2010-09-09"

Resources:        

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName: crud-sabc-ecs-task-role
      Policies:
      - PolicyName: crud-sabc-policy-read-secrets
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "secretsmanager:GetSecretValue"
            Resource: 
              - !ImportValue SecretDB
      - PolicyName: crud-sabc-policy-read-ssm
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "ssm:GetParameter"
            Resource: 
              -  "*"

  ECSService: 
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !ImportValue CrudECS
      DesiredCount: 1
      TaskDefinition: !Ref CrudTasKDefinition 

  CrudTasKDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - 
          Name: "clip_crud_project_sabc_container"
          Image: 109832253823.dkr.ecr.us-west-2.amazonaws.com/test-sabc:latest
          PortMappings:
            -
              ContainerPort: 5000
              HostPort: 0
              Protocol: "tcp"

      Cpu: "256"
      Memory: "512"
      Tags:
        - Key: Name
          Value: "clip_crud_project_sabc_task_definition"

