AWSTemplateFormatVersion: "2010-09-09"

Resources:

# ---------- SUBNET GROUP ----------------
  CrudappDBGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: String
      DBSubnetGroupName: String
      SubnetIds: 
        - !ImportValue DBSubnetA 
        - !ImportValue DBSubnetB
      Tags: 
        - Key: Name
          Value: clip_crud_project_sabc_rds


# ---------- SECRETS AND SSM ----------------

  SecretDBPass:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Secret for RDS databse"
      GenerateSecretString:
        ExcludeCharacters: '"@/'
        GenerateStringKey: "password"
        PasswordLength: 30
        RequireEachIncludedType: false
        SecretStringTemplate: '{"username": "admin"}'
      Name: "DBPass"
      Tags:
        - Key: Name
          Value: clip_crud_project_sabc_secret_db
  
  SSMDBEndPoint:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DB cluster endpoint"
      Name: /SABC/CrudProject/RDS/EndPoint
      Type: String 
      Value: !GetAtt DBCLUSTER.Endpoint.Address

# ---------- DB CLUSTER ----------------

  DBCLUSTER:
    Type: AWS::RDS::DBCluster
    Properties:
      DBSubnetGroupName: !Ref CrudappDBGroup
      DatabaseName: "crudapp"
      Engine: "aurora-mysql"
      EngineMode: "serverless"
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref SecretDBPass, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref SecretDBPass, ':SecretString:password}}' ]]
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 16
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      Tags:
        - Key: Name
          Value: clip_crud_project_sabc_rds
      UseLatestRestorableTime: false
      VpcSecurityGroupIds: 
        - !ImportValue DBSG

