AWSTemplateFormatVersion: "2010-09-09"

Resources:        

# ---------- ROLE FOR TASK ----------------
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName: crud-sabc-ecs-task-role
      Policies:
      - PolicyName: crud-sabc-policy-read-secrets
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "secretsmanager:GetSecretValue"
            Resource: 
              - !ImportValue SecretDB
      - PolicyName: crud-sabc-policy-read-ssm
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "ssm:GetParameter"
            Resource: 
              -  "*"
      - PolicyName: crud-sabc-policy-ecr
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "ecr:GetAuthorizationToken"
            - "ecr:BatchCheckLayerAvailability"
            - "ecr:GetDownloadUrlForLayer"
            - "ecr:BatchGetImage"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: 
              -  "*"

# ---------- Service ----------------

  ECSService: 
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !ImportValue CrudECS
      LoadBalancers:
        - ContainerName: "clip_crud_project_sabc_container"
          ContainerPort: 5000
          TargetGroupArn: !Ref AppTargetGroup
      DesiredCount: 2
      TaskDefinition: !Ref CrudTasKDefinition 

# ---------- SERVICE ----------------

  CrudTasKDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - 
          Name: "clip_crud_project_sabc_container"
          Image: 109832253823.dkr.ecr.us-west-2.amazonaws.com/test-sabc:latest
          PortMappings:
            -
              ContainerPort: 5000
              HostPort: 0
              Protocol: "tcp"
          Environment:
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region
      Cpu: "256"
      Memory: "512"
      Tags:
        - Key: Name
          Value: "clip_crud_project_sabc_task_definition"

# ---------- LISTENER AND TARGET GROUP ----------------
  LBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup
      LoadBalancerArn: !ImportValue  AppLBE
      Port: 80
      Protocol: "HTTP"

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "Crud-project-sabc"
      Port: 80
      Protocol: "HTTP"
      TargetType: "instance"
      VpcId: !ImportValue CrudVPC
      Tags:
        - Key: Name
          Value: crud-sabc-tg

# ---------- ALARMS ----------------
  CPUAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Cluster alert cpu usage alarm
      AlarmActions: 
        - !ImportValue EmailSNS
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '50'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: ClusterName
        Value: !ImportValue CrudECS

  CPUAlarmCritical:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Cluster critical cpu usage alarm
      AlarmActions: 
        - !ImportValue EmailSNS
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '80'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: ClusterName
        Value: !ImportValue CrudECS

  CPUAlarmDemo:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Cluster alarm super sensible for demo purposes
      AlarmActions: 
        - !ImportValue EmailSNS
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Maximum
      Period: '60'
      EvaluationPeriods: '1'
      Threshold: '5'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: ClusterName
        Value: !ImportValue CrudECS

  UnhealthyInstances:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Check if there is only one instance healthy running
      AlarmActions: 
        - !ImportValue EmailSNS
      MetricName: HealthyHostCount 
      Namespace: AWS/ApplicationELB
      Statistic: Minimum
      Period: '30'
      EvaluationPeriods: '3'
      Threshold: '1'
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
      - Name: TargetGroup
        Value: !Ref AppTargetGroup
      - Name:  LoadBalancer
        Value: !ImportValue AppLBE
